-- V1: baseline schema matching JPA entity com.liliya.eventpulse.entity.Event
-- Naming: Spring Boot CamelCaseToUnderscoresNamingStrategy
-- Types: Hibernate PostgreSQLDialect defaults (no @Column overrides on the entity)
-- Bean Validation annotations do not create database constraints

CREATE TABLE event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(255),
    event_date      DATE,
    attendance      INTEGER,
    wifi_estimate   INTEGER,
    network_usage   DOUBLE PRECISION,
    notes           VARCHAR(255),
    PRIMARY KEY (id)
);
