-- V3: persistent application users for Spring Security
-- Passwords are BCrypt hashes only (plaintext never stored).
-- Flyway treats $ as placeholder start; escape each $ as $$.

CREATE TABLE app_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username        VARCHAR(50)  NOT NULL,
    password_hash   VARCHAR(100) NOT NULL,
    role            VARCHAR(20)  NOT NULL,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uq_app_user_username UNIQUE (username),
    CONSTRAINT ck_app_user_role CHECK (role IN ('ADMIN', 'VIEWER'))
);

-- Demo seed users (hashes for EventPulse-Admin! / EventPulse-Viewer! — see README)
INSERT INTO app_user (username, password_hash, role, enabled) VALUES
    (
        'admin',
        '$$2a$$10$$AIACvUD9Bqo5CVrCPbB8yuygytxCgatzqPg/h4gfa606J3pUJtwu.',
        'ADMIN',
        TRUE
    ),
    (
        'viewer',
        '$$2a$$10$$cKz9KiES6C82yhB.Zve3/OGFuZoud7ts9IPzXdbk9NcQol4KQ4SlC',
        'VIEWER',
        TRUE
    );
